language: php
dist: trusty
php:
 - 7.0
 - 7.1
 - 7.2

services:
 - docker

branches:
  only:
    - "master"

env:
  matrix:
    - PHPUNIT=true
addons:
  apt:
    packages:
      - libsdl2-dev
      - libhidapi-dev
      - libudev-dev
      - libusb-1.0-0-dev

matrix:
  exclude:
    - php: 7.2
      env: PHPUNIT=true
  include:
    - php: 7.2
      env: PHPUNIT=true COVERAGE=true CODE_STYLE=true
    - php: 7.2
      env: INTEGRATION=true TREZOR_BRIDGE_VERSION=v2.0.10 COVERAGE=true

install:
 - composer install

before_script:
 - if [ "${COVERAGE}" != "true" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then phpenv config-rm xdebug.ini && echo "xdebug disabled"; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
 - if [ "${INTEGRATION}" = "true" ]; then
     eval $(gimme 1.9);
   fi
 - tool/run_phpunit_tests.sh
 - BRIDGE_PATH=$GOPATH/bin/trezord-go EMULATOR_PATH=tool/emulator/trezor-mcu/build/trezor-emulator64-master tool/run_integration_tests.sh
 - tool/run_codestyle_tests.sh

after_success:
- if [ "${COVERAGE}" = "true" ] ; then make scrutinizer; fi
